---
name: Elaine Kearney
position: "Postdoctoral Research Associate"
address: "Dept. of Speech, Language & Hearing Sciences, Boston University"
#phone: 
www: elaine-kearney.com
email: ekearney@bu.edu
twitter: ek_kearney
github: elainekearney
aboutme: "Speech scientist focused on the sensorimotor control of speech production in individuals with and without motor speech disorders. I conduct both basic science and clinical research that leverages my expertise in behavioral, computational modeling, and neuroimaging methods. The long-term aim of my research program is to expand the evidence-based treatment options available to those with communication disorders."
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: "000000"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      message = FALSE)
source("../scripts/install.R")
```

```{r get data, include=FALSE}
## Education
edu <- read_csv(here::here("data", "education.csv"))

## Jobs
jobs <- read_csv(here::here("data", "jobs.csv"))

## Publications - change google id here
pubs <- read_csv(here::here("data", "publications.csv")) %>% 
  arrange(desc(when))

## Software
software <- read_csv(here::here("data", "software.csv")) %>% 
  arrange(desc(when)) 

## Teaching
teaching <- read_csv(here::here("data", "teaching.csv"))

## Presentations
presentations <- read_csv(here::here("data", "presentations.csv"))

## Awards
awards <- read_csv(here::here("data", "awards.csv"))

## Skills
skills <- read_csv(here::here("data", "skills.csv")) %>% 
  group_by(category) %>% 
  mutate(skill = paste(skill, collapse = ", ")) %>% 
  ungroup %>% 
  unique

## Affiliations
affiliations<- read_csv(here::here("data", "affiliations.csv"))

## Service
service <- read_csv(here::here("data", "service.csv"))

## Mentoring
mentor <- read_csv(here::here("data", "mentoring.csv"))
```

# Education 
```{r}
detailed_entries(edu, 
                 when = glue("{start_date}--{end_date}"),
                 with = degree,
                 where = loc,
                 what = uni,
                 why = details)

```

# Research Employment

```{r research}
jobs %>% 
  detailed_entries(
    with = role,
    when = glue("{start_date}--{end_date}"),
    what = company,
    where = where,
    why = details)
```

# Research Awards and Honors

```{r}
awards %>% 
  detailed_entries(what = with, 
                   with = what, 
                   when = when, 
                   where = where, 
                   why = amount)
```

# Professional Affiliations

```{r}
affiliations %>% 
  detailed_entries(what = role,
                   when = glue("{start_date}--{end_date}"),
                   with = details)
```
# Service

```{r}
service %>% 
  detailed_entries(what = role,
                   when = glue("{start_date}--{end_date}"),
                   with = type,
                   why = details,
                   where = where)
```
# Publications
*Available for download at https://elaine-kearney.com/publication/*

## Peer-Reviewed
```{r}
pubs %>% 
  dplyr::filter(type=="peer_review") %>% 
  detailed_entries(
    what = with,
    when = when,
    with = what,
    where = where,
    why = doi,
    .protect = TRUE
  )
```

## Proceedings
```{r}
pubs %>% 
  dplyr::filter(type=="proceedings") %>% 
  detailed_entries(
    what = with,
    when = when,
    with = what,
    where = where,
    .protect = TRUE
  )
```

# Presentations

## International

**Invited**
```{r}
presentations %>%
  dplyr::filter(loc=="international", invited) %>%
  detailed_entries(what = with, 
                   when = when,
                   with = glue("{what} ({type})"),
                   where = where,
                   why = why,
                   .protect = TRUE)
```

**Conference**
```{r}
presentations %>%
  dplyr::filter(loc=="international", !invited) %>%
  detailed_entries(what = with,
                   when = when,
                   with = glue("{what} ({type})"),
                   where = where,
                   why = why,
                   .protect = TRUE)
```

## National

**Invited**
```{r}
presentations %>%
  dplyr::filter(loc=="national", invited) %>%
  detailed_entries(what = with,
                   when = when,
                   with = glue("{what} ({type})"),
                   where = where,
                   why = why,
                   .protect = TRUE)
```
**Conference**

```{r}
presentations %>%
  dplyr::filter(loc=="national", !invited) %>%
  detailed_entries(what = with,
                   when = when,
                   with = glue("{what} ({type})"),
                   where = where,
                   why = why,
                   .protect = TRUE)
```
## Workshops
```{r}
presentations %>%
  dplyr::filter(loc=="workshop") %>%
  detailed_entries(what = with, 
                   when = when,
                   with = glue("{what} ({type})"),
                   where = where,
                   why = why,
                   .protect = TRUE)
```

# Software

```{r}
software %>% 
  detailed_entries(what = with, with = what, when = when, where = where, why = why)
```
# Research Mentoring
```{r}
mentor %>% 
  detailed_entries(what = uni, 
                   with = student, 
                   when = when, 
                   where = where, 
                   why = details)
```

# Teaching

## Certificate
```{r}
teaching %>%
    dplyr::filter(cert=="yes") %>%
    detailed_entries(
    with = role,
    when = when,
    what = company,
    where = where)
```
## Experience
```{r}
teaching %>%
    dplyr::filter(cert=="no") %>%
    detailed_entries(
    with = role,
    when = when,
    what = company,
    where = where,
    why = details)
```

# Technical Skills

```{r}
skills %>% 
  detailed_entries(what = skill, 
                   with = category)
```
\pagebreak